config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#main"
  resources :services
  resources :checks

  get '/sidebar', to: 'application#sidebar', as: 'sidebar'
  get '/dashboard', to: 'application#dashboard', as: 'dashboard'
  # get '/service/id', to: 'service#view', as: 'service'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :service
  has_many :results, dependent: :destroy

  def self.init(type, config)
    clazz = self.const_get type.to_s.camelize
    clazz.new config.with_indifferent_access
  end
end

app/models/down.rb
class Down < ApplicationRecord
  belongs_to :service

  def duration
    to = self.to
    return nil unless to
    to - self.from
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :check
end

app/models/service.rb
class Service < ApplicationRecord
  self.inheritance_column = :_type
  enum type: %i[ping tcp udp http cert].collect { |k| [k, k.to_s] }.to_h.freeze
  attribute :interval, :duration
  validates :type, inclusion: { in: self.types.keys }
  has_many :checks, dependent: :destroy
  has_many :downs, dependent: :destroy

  def check!
    last     = self.last_check
    interval = self.interval
    if interval
      delay = Time.now - last.created_at
      return if delay < interval
    end

    check  = Check.init self.type, self.config
    values = check.process
    result = check.ok?

    check = self.checks.create! result: result
    values.each { |k, v| check.results.create! key: k, value: v }

    if last
      case [last.result, result]
      when [true, false]
        down = self.downs.create! from: check.created_at
        NotifierMailer.with(service: self, down: down).service_fail.deliver_now
      when [false, true]
        down = self.last_down
        down.update! to: check.created_at if down
        NotifierMailer.with(service: self, down: down).service_recover.deliver_now
      end
    end
  end

  UPTIME_DURATIONS = [1.year, 1.month, 1.week, 1.day].freeze

  def uptime
    first_check = self.checks.order(created_at: :asc).limit(1).first
    return nil unless first_check

    now    = Time.now.utc
    uptime = UPTIME_DURATIONS.map { |d| [d, 0.second] }.to_h
    ago    = UPTIME_DURATIONS.map { |d| [d, d.ago(now).utc] }.to_h
    start  = ago.fetch UPTIME_DURATIONS.first

    self.downs.where('"to" >= ?', start).each do |down|
      UPTIME_DURATIONS.each do |duration|
        start            = ago[duration]
        uptime[duration] += down.to.utc - [start, down.from.utc].max if start <= down.to
      end
    end

    check_start = first_check.created_at.utc
    uptime.map do |duration, downtime|
      start = ago[duration]
      max   = [check_start, start].max
      diff  = (now - max).seconds
      percentage = 1 - downtime / diff
      [duration, percentage]
    end.to_h
  end

  def last_check
    self.checks.order(created_at: :desc).limit(1).first
  end

  def last_down
    self.downs.order(created_at: :desc).limit(1).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def main
    @services = Service.all
    @checks = Check.all
  end

  def sidebar
    @services = Service.all
    sidebar = []
    percent = 100
    @services.each do |s|
      ref = nil
      unless s.config[:http].nil?
        ref = s.config[:http]
      end
      sidebar.push(
          {
              percent: percent,
              type: s.type,
              ref: ref,
              name: s.name,
              error: nil
          })
      percent -= 10
    end
    render json: sidebar
  end

  def dashboard
    @services = Service.all
    @checks = Check.all
    dashboard = {
        total_services: @services.size,
        total_checks: @checks.size,
        stats: @services
    }
    render json: dashboard
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def show
    render json: @service
  end

  def new
    @service = Service.new
  end

  CONFIG_PARAMS = {
      ping: %i[host],
      http: %i[url code],
      tcp: %i[host port],
      udp: %i[host port]
  }

  def create
    type = params[:service][:type].to_sym
    config = params[:service].slice *CONFIG_PARAMS[type]
    p = { name: params[:service][:name], type: type, config: config }

    @service = Service.create! **p
    redirect_to @service, notice: t('notice.service.created', service: @service.name)
  end

  def edit
  end

  def update
    type = params[:service][:type].to_sym
    config = params[:service].slice *CONFIG_PARAMS[type]
    p = { id: params[:id], name: params[:service][:name], type: type, config: config }

    if @service.update(p)
      redirect_to @service, notice: t('notice.service.updated', service: @service.name)
    else
      render :edit
    end
  end

  private
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(
      :id,
      :name,
      :type,
      :config
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'info' then "alert alert-info"
    when 'notice','success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/application/main.html.erb
<h1 class="text-steal">Dashboard</h1>

<h2>Quick stats</h2>

<p>You have defined <%= @services.size %> services.</p>

<p>A total of <%= @checks.size %> checks were performed.</p>

<h2 class="text-dark">Latest events for all services</h2>

<!--<table class="table">-->
<!--  <thead class="thead-dark">-->
<!--    <tr>-->
<!--      <th>Event</th>-->
<!--      <th>Type</th>-->
<!--      <th>Service</th>-->
<!--      <th>Datetime</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
  <%# @services.each do |service| %>
<!--    <tr>-->
<!--      <td></td>-->
<!--      <td><%#= service.type %></td>-->
<!--      <td><%#= link_to service.name, service %></td>-->
<!--      <td><%#= service.updated_at %></td>-->
<!--    </tr>-->
  <%# end %>
<!--  </tbody>-->
<!--</table>-->

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-light text-center p-4">
  <div>
    Monit is a free web application to monitor your servers, developped by
    <a href="https://imirhil.fr/">Aeris</a> (backend) and <a href="https://norore.fr">Norore</a> (frontend) under [license]
  </div>
  <div>
    Icon made by <a href="https://norore.fr">Norore</a> under [license]
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="mainmenu" role="navigation">
    <%= link_to root_path, locale: I18n.locale.to_s, class: 'navbar-brand' do
      image_tag(asset_path('logo.png'), size: '50', alt: "Monit logo") + ' ' + Monit
    end
    %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
             role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% lang = I18n.locale.to_s %>
            <%= t("locale.#{lang}") %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% liste = %i[fr en]
               liste.each do |l| %>
              <% unless l == lang %>
                <div class="dropdown-item">
                  <%= link_to (t("locale.#{l}")), locale: l %>
                </div>
              <% end %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<%= link_to new_service_url, class: %i[add] do %>
  <i class="fa fa-plus"></i> Add a service
<% end %>

<% @services.each do |service| %>
  <div class="m-1 row bg-light">
    <div class="col-1">
      <span class="badge badge-secondary">0%</span>
    </div>
    <div class="col-3">
      <span class="badge badge-pill badge-secondary">
        <%= service.type %>
      </span>
    </div>
    <div class="col-6">
      <%= link_to service.name, service %>
    </div>
    <div class="col-2 text-right">
      <%= service.updated_at.strftime('%d/%m/%y %H:%M') %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= favicon_link_tag asset_path 'logo.png' %>
  </head>

  <body>
    <%#= render 'layouts/header' %>

<!--    <main class="container-fluid">-->
<!--      <div id="container" class="row">-->
<!--        <aside id="sidebar" class="col-sm-2">-->
          <%#= render 'layouts/sidebar' %>
<!--        </aside>-->

<!--        <div id="content" class="col-sm-10">-->
            <%# flash.each do |key, value| %>
<!--              <div class="<%#= flash_class(key) %> alert-dismissible fade show mt-4">-->
<!--                <button type="button" class="close" data-dismiss="alert" aria-label="Close">-->
<!--                  <span aria-hidden="true">&times;</span>-->
<!--                </button>-->
                <%#= value %>
<!--              </div>-->
            <%# end %>

            <%#= yield %>
<!--        </div>-->
<!--      </div>-->
<!--    </main>-->
    <%#= render 'layouts/footer' %>
  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: service, local: true) do |form| %>
  <% if service.errors.any? %>
    <div class="card text-white bg-danger mb-2">
      <div class="card-header">
        <%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:
      </div>

      <div class="card-body">
        <ul>
          <% service.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, t("service.form.name"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.text_field :name, class: %i[form-control] %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :type, t("service.form.type"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.select :type,  options_for_select(
          %i[ping tcp udp http cert].collect { |n| [ t("service.form.type.#{n}"), n ] }, form.object.type
        ), {}, onchange: 'createConfig(this)', class: %i[form-control] %>
    </div>
  </div>

  <!-- type of service will define config fields required by app -->
  <div id="host" class="form-group row">
    <%= form.label :host, t("service.form.host"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.text_field :host, class: %i[form-control] %>
    </div>
  </div>

  <div id="port" class="form-group row">
    <%= form.label :port, t("service.form.port"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.text_field :port, class: %i[form-control] %>
    </div>
  </div>

  <div id="link" class="form-group row"> <!-- id named link for aesthetic purpose only on JS part -->
    <%= form.label :url, t("service.form.url"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.text_field :url, class: %i[form-control] %>
    </div>
  </div>

  <div id="code" class="form-group row">
    <%= form.label :code, t("service.form.code"), class: %i[col-sm-2 col-form-label] %>
    <div>
      <%= form.text_field :code, class: %i[form-control] %>
    </div>
  </div>

  <div class="actions text-right">
    <%= link_to t('button.cancel'), root_path, class: %i[btn btn-secondary] %>&nbsp;
    <%= form.submit t('button.submit'), class: %i[btn btn-primary] %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1><%= t('service.edit.title', service: @service.name) %></h1>

<%= render 'form', service: @service %>

<%= link_to t('home'), root_path %>

app/views/services/new.html.erb
<h1><%= t('service.new.title') %></h1>

<%= render 'form', service: @service %>

app/views/services/show.html.erb
<h1><%= @service.name %></h1>

<strong>Type of service:</strong> <%= @service.type %><br>
<strong>Config:</strong> <%= @service.config %>